### ISSUE TITLE
Question: scopes?

### ISSUE THREAD

**Issue by renarsvilnis** [conwetlab/passport-fiware-oauth#1]
What kind of scopes are available for querying user data? Can't find any documentation on the fiware website.

Only scope I could find is on this repo example code showing `{scope: 'all_info'}`. 

```javascript
router.get('/fiware', passport.authenticate('fiware', {scope: 'all_info'}));
```

**Comment by aitormagan** [comment]
I cannot provide you more information in this regard. I think that `all_info` is the only scope available since I have not seen another. Maybe, @aalonsog can provide you more information about this!

**Comment by aalonsog** [comment]
As Aitor says, we have only a scope there.

**Comment by renarsvilnis** [comment]
Thanks for the response!
