### ISSUE TITLE
Feature: Normalised profile data

### ISSUE THREAD

**Issue by renarsvilnis** [conwetlab/passport-fiware-oauth#2]
Integrating `passport-fiware-oauth` strategy in my application. While debugging `profile` object saw that it contains `email: <string>` instead of the [normalised passport schema](http://passportjs.org/docs/profile) `emails: <Array>`. Having it normalised would result in cleaner code, as no need to add extra if's.

**EDIT**
Made a pull request.

**Comment by aitormagan** [comment]
Thank you for your contribution. We have accepted it and updated the tests. The `0.1.6` version has been released so you can now download it and find your changes! :)
